#!/usr/bin/env bash
# Move the object database's generated files between this checkout and a GitHub Release.
#
# They are not committed: 148 MB, nearly all of it map renders that are replaced wholesale every
# time build-database.py runs, so each regeneration would add another copy to the history. CI
# cannot regenerate them either — that needs gecko and the game's .dat files. So the files live in
# a release, and the tag the site builds against is pinned in scripts/database-release.txt.
#
#   scripts/database-release.sh fetch            # download the pinned release into static/
#   scripts/database-release.sh publish <tag>    # upload what build-database.py wrote, then pin it
set -euo pipefail

cd "$(dirname "$0")/.."
REPO=JanSimek/fallout2-guide
ASSET=object-database.tar.gz
PIN=scripts/database-release.txt
# Relative to static/ — every directory build-database.py writes into.
DIRS=(data img/db img/maps)

case "${1:-}" in
  fetch)
    tag=$(<"$PIN")
    echo "fetching object database $tag"
    gh release download "$tag" --repo "$REPO" --pattern "$ASSET" --output - | tar -xz -C static
    ;;

  publish)
    tag=${2:?usage: $0 publish <tag>}
    for dir in "${DIRS[@]}"; do
      [[ -d static/$dir ]] || { echo "static/$dir is missing — run build-database.py first" >&2; exit 1; }
    done
    tmp=$(mktemp -d)
    trap 'rm -rf "$tmp"' EXIT
    # macOS tar would otherwise pack extended attributes and ._ files, which GNU tar on the CI
    # runner warns about line by line.
    COPYFILE_DISABLE=1 tar --no-xattrs --exclude .DS_Store -czf "$tmp/$ASSET" -C static "${DIRS[@]}"
    gh release create "$tag" "$tmp/$ASSET" --repo "$REPO" --latest=false \
      --title "Object database ($tag)" \
      --notes "Generated by \`website/scripts/build-database.py\`. Not a guide release: the deploy workflow downloads this archive into \`website/static/\` before building."
    echo "$tag" > "$PIN"
    echo "pinned $tag in $PIN — commit it"
    ;;

  *)
    echo "usage: $0 fetch | publish <tag>" >&2
    exit 2
    ;;
esac
