#!/usr/bin/env bash
# Keep the object database's generated files in a GitHub Release, in step with RPU.
#
# They are not committed: 148 MB, nearly all of it map renders that are replaced wholesale every
# time build-database.py runs, so each regeneration would add another copy to the history. CI
# cannot regenerate them either — that needs gecko and the game's .dat files, which stay on this
# machine. So they live in a release, and the tag the site builds against is pinned in
# scripts/database-release.txt.
#
#   scripts/database-release.sh update           # rebuild + publish + pin if RPU has moved on
#   scripts/database-release.sh fetch            # download the pinned release into static/
#   scripts/database-release.sh publish <tag>    # upload what is in static/, then pin it
#
# `update` is what the pre-commit hook runs. It is one API call unless RPU has shipped a release
# the pin does not match, and it never blocks a commit on a machine that cannot build.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO=JanSimek/fallout2-guide
ASSET=object-database.tar.gz
PIN=scripts/database-release.txt
# Relative to static/ — every directory build-database.py writes into.
DIRS=(data img/db img/maps)

# Bump when build-database.py's output changes (a new file, a new field). Part of the release tag, so
# the hook rebuilds for a new generator as well as for a new RPU release.
DATABASE_REVISION=2

# The release line the database follows. 2.4.x is 2.3.x plus Pixote's updated maps.
RPU_REPO=BGforgeNet/Fallout2_Restoration_Project
RPU_LINE=2.4
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/fallout2-guide"
GECKO_DIR=${GECKO_DIR:-$HOME/Development/geck-map-editor/build}
FALLOUT2_DATA=${FALLOUT2_DATA:-$HOME/Development}

say() { echo "database: $*" >&2; }

# Replace static/'s database directories with the ones under $1, so nothing from an older build
# lingers — build-database.py skips sprites that already exist, and a map RPU drops would stay.
install_into_static() {
  for dir in "${DIRS[@]}"; do
    rm -rf "static/$dir"
    mkdir -p "$(dirname "static/$dir")"
    mv "$1/$dir" "static/$dir"
  done
}

fetch() {
  local tag tmp
  tag=$(<"$PIN")
  say "fetching $tag"
  tmp=$(mktemp -d)
  gh release download "$tag" --repo "$REPO" --pattern "$ASSET" --output - | tar -xz -C "$tmp"
  install_into_static "$tmp"
  rm -rf "$tmp"
}

publish() {
  local tag=$1 src=$2 tmp
  for dir in "${DIRS[@]}"; do
    [[ -d $src/$dir ]] || { say "$src/$dir is missing — run build-database.py first"; exit 1; }
  done
  tmp=$(mktemp -d)
  # macOS tar would otherwise pack extended attributes and ._ files, which GNU tar on the CI
  # runner warns about line by line.
  COPYFILE_DISABLE=1 tar --no-xattrs --exclude .DS_Store -czf "$tmp/$ASSET" -C "$src" "${DIRS[@]}"
  gh release create "$tag" "$tmp/$ASSET" --repo "$REPO" --latest=false \
    --title "Object database ($tag)" \
    --notes "Generated by \`website/scripts/build-database.py\`. Not a guide release: the deploy workflow downloads this archive into \`website/static/\` before building."
  rm -rf "$tmp"
  echo "$tag" > "$PIN"
  say "published and pinned $tag"
}

# The newest non-draft release on RPU_LINE. curl with a timeout rather than gh, so a dead network
# costs a commit five seconds instead of hanging it; gh's token only lifts the rate limit.
latest_rpu() {
  local auth=() token
  if token=$(gh auth token 2>/dev/null); then auth=(-H "Authorization: Bearer $token"); fi
  curl -fs --max-time 5 ${auth[@]+"${auth[@]}"} "https://api.github.com/repos/$RPU_REPO/releases?per_page=30" |
    python3 -c '
import json, re, sys
line = re.escape(sys.argv[1])
for release in json.load(sys.stdin):
    if not release["draft"] and not release["prerelease"] and re.fullmatch(rf"v{line}\.\d+", release["tag_name"]):
        print(release["tag_name"])
        break
else:
    sys.exit(1)
' "$RPU_LINE" 2>/dev/null
}

# Fail loudly on a build that would publish holes: an unreadable map, a render maps.json names but
# nobody wrote, or an export that came back empty.
check_build() {
  python3 - "$1" <<'EOF'
import json, os, sys
out = sys.argv[1]
entities = json.load(open(f'{out}/data/entities.json'))
protos = json.load(open(f'{out}/data/protos.json'))['protos']
maps = json.load(open(f'{out}/data/maps.json'))['maps']
problems = []
if entities['mapsUnreadable']:
    problems.append(f"{len(entities['mapsUnreadable'])} unreadable map(s)")
if not entities['entities'] or not protos or not maps:
    problems.append('an empty export')
missing = [image for m in maps for level in m['levels'] for key in ('base', 'detail')
           if (image := level.get(key)) and not os.path.exists(f'{out}/img/maps/{image}')]
if missing:
    problems.append(f'{len(missing)} map render(s) missing, e.g. {missing[0]}')
if problems:
    sys.exit('database: refusing to publish — ' + '; '.join(problems))
print(f"database: {len(entities['maps'])} maps, {len(entities['entities'])} entities, "
      f"{len(protos)} protos, {sum(len(m['levels']) for m in maps)} renders", file=sys.stderr)
EOF
}

update() {
  local latest tag pinned src out f
  command -v gh >/dev/null || { say "gh is not installed — not checking RPU"; return 0; }
  if ! latest=$(latest_rpu); then
    say "could not reach GitHub to check RPU releases — skipped"
    return 0
  fi
  tag="database-rpu-$latest-r$DATABASE_REVISION"
  pinned=$(<"$PIN")
  [[ $pinned == "$tag" ]] && return 0

  say "pinned $pinned, but the current build would be $tag"
  if gh release view "$tag" --repo "$REPO" >/dev/null 2>&1; then
    say "$tag is already published — pinning it"
    echo "$tag" > "$PIN"
    fetch
    return 0
  fi

  local missing=()
  for f in "$GECKO_DIR/gecko-cli" "$GECKO_DIR/gecko-mcp" "$FALLOUT2_DATA/master.dat" "$FALLOUT2_DATA/critter.dat"; do
    [[ -e $f ]] || missing+=("$f")
  done
  command -v cwebp >/dev/null || missing+=(cwebp)
  if (( ${#missing[@]} )); then
    say "cannot rebuild on this machine, missing: ${missing[*]} — the database stays at $pinned"
    return 0
  fi

  # A clean checkout of the release, separate from the RPU tree the gecko MCP reads, which may be
  # on another branch or carry local edits. The release's compiled scripts are not needed: the export
  # only reads scripts.lst.
  src="$CACHE/rpu-$latest"
  if [[ ! -d $src ]]; then
    say "downloading RPU $latest (about 1 GB, once)"
    rm -rf "$src.partial"
    git -c advice.detachedHead=false clone --quiet --depth 1 --branch "$latest" "https://github.com/$RPU_REPO.git" "$src.partial"
    mv "$src.partial" "$src"
  fi

  out="$CACHE/database-$latest"
  rm -rf "$out"
  say "rebuilding for RPU $latest — this takes a while (skip with SKIP_DATABASE_UPDATE=1)"
  RPU_VERSION="$latest" FALLOUT2_RPU="$src" FALLOUT2_DATA="$FALLOUT2_DATA" \
    GECKO_MCP="$GECKO_DIR/gecko-mcp" GECKO_CLI="$GECKO_DIR/gecko-cli" \
    python3 scripts/build-database.py --strict --out "$out" >&2
  check_build "$out"
  publish "$tag" "$out"
  install_into_static "$out"
  rm -rf "$out"
  # Older release checkouts are dead weight once a newer one has been published.
  find "$CACHE" -maxdepth 1 -name 'rpu-v*' ! -name "rpu-$latest" -exec rm -rf {} +
}

case "${1:-}" in
  update) update ;;
  fetch) fetch ;;
  publish) publish "${2:?usage: $0 publish <tag>}" static ;;
  *)
    echo "usage: $0 update | fetch | publish <tag>" >&2
    exit 2
    ;;
esac
